### ISSUE TITLE
Themen/Speaker für erste Meetups

### ISSUE THREAD

**Issue by rstropek** [coding-club-linz/rust-meetup-concept#8]
## Todos

- [x] Kontakt zu anderen Rust-Meetups in Österreich aufnehmen und nach Gastvorträgen fragen
- [ ] _Call for Participation_ auf Social Media
- [x] Aufsetzen CfP-Plattform (Vorschlag: dauerhafter Sessionize CfP)

## Themen

Vorschlag: Besonders am Anfang geben wir Themen für Treffen vor, für die wir Leute suchen, die Kurzvorträge dazu halten.

* Cargo
* Fundamentals (z.B. Datentypen, Funktionen, Kontrollfluss, Collections etc.). Vergleich von Rust Fundamentals mit anderen Sprachen. Was ist ähnlich? Was ganz anders?
* Memory Ownership
* Structs, Traits und Enums
* Funktionale Programmierung mit Rust
* Concurrent/async Programming 
* Packages, Crates, Modules
* Testautomatisierung
* Web APIs mit Rust
* CLIs mit Rust
* Interop (C/C++, .NET)

**Comment by rstropek** [comment]
CfP in Sessionize ist aufgesetzt: https://sessionize.com/rust-linz/

Erwarte Freischaltung wg. Non-Profit in den nächsten 24-48 Stunden.

**Comment by rstropek** [comment]
Meetuporganisator Rust Wien kontaktiert, warte auf Rückmeldung.

**Comment by rstropek** [comment]
* Sessionize ist fertig und aktiviert: https://sessionize.com/rust-linz/
* Leider bisher noch keine Rückmeldung von Rust Wien

**Comment by rstropek** [comment]
Bei offizieller Rust Community Emailadresse nachgefragt.
